#!/usr/bin/env bash
# Picks free host ports into .env (created on first run), then runs docker compose.
#   ./run.sh            docker compose up --build -d, then print the URLs
#   ./run.sh <args>     docker compose <args> (for example: ./run.sh down)
set -eu
cd "$(dirname "$0")"

# Host port variables and their preferred defaults.
PORTS="SITE_PORT=8080"

print_urls() {
  echo "Site: http://localhost:$(port_of SITE_PORT)"
}

# ---- generic part (identical in every repo) ----
is_busy() { (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null; }

env_get() { [ -f .env ] && sed -n "s/^$1=//p" .env | tail -n 1 | tr -d '\r' || true; }

env_set() {
  if grep -q "^$1=" .env; then
    awk -v k="$1" -v v="$2" 'BEGIN{FS=OFS="="} $1==k{print k "=" v; next} {print}' .env > .env.tmp && mv .env.tmp .env
  else
    [ -z "$(tail -c 1 .env)" ] || echo >> .env
    printf '%s=%s\n' "$1" "$2" >> .env
  fi
}

port_of() {
  p=$(env_get "$1")
  if [ -z "$p" ]; then
    for spec in $PORTS; do [ "${spec%%=*}" = "$1" ] && p=${spec#*=}; done
  fi
  echo "$p"
}

choose_ports() {
  if [ ! -f .env ]; then
    printf '%s\n' "# Generated by run.sh: host ports chosen because the defaults were busy or to avoid" \
      "# clashes with other stacks. Edit to pin ports, or delete this file to pick again." > .env
  fi
  picked=" "
  for spec in $PORTS; do
    var=${spec%%=*}
    port=$(env_get "$var")
    case $port in ''|*[!0-9]*) port=${spec#*=} ;; esac
    start=$port
    while is_busy "$port" || case $picked in *" $port "*) true ;; *) false ;; esac; do
      port=$((port + 1))
    done
    picked="$picked$port "
    [ "$port" = "$start" ] || echo "$var: port $start is busy, using $port"
    [ "$port" = "$(env_get "$var")" ] || env_set "$var" "$port"
  done
}

BUILD=--build
if [ -n "$(docker compose ps --status running -q)" ]; then
  echo "Stack already running: leaving ports unchanged and skipping the rebuild."
  echo "(To rebuild after code changes: ./run.sh up --build -d)"
  BUILD=
else
  choose_ports
fi

if [ $# -gt 0 ]; then
  exec docker compose "$@"
fi
docker compose up $BUILD -d
print_urls
